import type { Metadata } from "next";
import { site } from "@/lib/site";

/**
 * Open Graph and Twitter metadata for any page other than the home page.
 *
 * Next replaces — rather than merges — the root layout's `openGraph` when a
 * page sets its own, which silently drops the share image, site name and
 * locale. Building both objects here keeps every page's social card complete.
 * The image is the route generated by app/opengraph-image.tsx.
 */
export function socialMetadata({
  title,
  description,
  path,
}: {
  title: string;
  description: string;
  path: string;
}): Pick<Metadata, "openGraph" | "twitter"> {
  const image = {
    url: "/opengraph-image",
    width: 1200,
    height: 630,
    alt: `${site.legalName} — web design in ${site.locality}, ${site.region}`,
  };
  return {
    openGraph: {
      type: "website",
      siteName: site.legalName,
      locale: "en_GB",
      title,
      description,
      url: `${site.url}${path}`,
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image.url],
    },
  };
}
